service: demo-serverless-go-auth0

frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x
  profile: serverless
  region: eu-west-2

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  auth:
    handler: bin/authorizer

  hello:
    handler: bin/hello
    events:
      - http:
          path: hello
          method: get
          authorizer: auth
